# Element wise Operations

In [3]:
import numpy as np


In [6]:
a=np.array([[4,5,6],[5,7,9]])
b=a=np.array([[5,2,3],[1,8,9]])

In [7]:
a,b


(array([[5, 2, 3],
        [1, 8, 9]]),
 array([[5, 2, 3],
        [1, 8, 9]]))

# Airthmetic Operations

In [8]:
np.add(a,b)

array([[10,  4,  6],
       [ 2, 16, 18]])

In [10]:
# a- b
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
np.power(a, 2)

array([[25,  4,  9],
       [ 1, 64, 81]])